[pytest]
pythonpath = .
testpaths = tests
addopts = -v
filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated.*:DeprecationWarning
    ignore:'crypt' is deprecated and slated for removal.*:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated.*:DeprecationWarning
